### ISSUE TITLE
Creating a migration file for a new JPA Entity

### ISSUE THREAD

**Issue by jjbuchan** [jjbuchan/docs#17]
By adding this configuration into a service's `application.yml` and running the service, it'll auto-generate a `create.sql` file in the project.  You can then copy the relevant line out of that file and use it in a new migrations file.

```
spring:
  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              create-source: metadata
              action: create
              create-target: create.sql
```
---
Example sql generated:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/4358210/94965828-667f1f00-04b9-11eb-96ce-f5e5106cbed8.png">

---
There might be other better ways to do this(?) but this worked for me.
