### ISSUE TITLE
How to connect to many servers at once

### ISSUE THREAD

**Issue by jjbuchan** [jjbuchan/docs#7]
I do this another way without knife.  Using https://github.com/wouterdebie/i2cssh I can type `i2cssh -c aep-ord` to open up a multi-tabbed window in iTerm containing all aeps in ord, and then broadcast the commands across all.

My config file has a similar setup for all server types for both prod and stage.

```
---
version: 2
broadcast: true
clusters:
  aep-dfw:
    hosts:
      - agent0.dfw1.com
      - agent1.dfw1.com
      - agent2.dfw1.com
      - agent3.dfw1.com
      - agent4.dfw1.com
      - agent5.dfw1.com
  aep-ord:
    hosts:
      - agent0.ord1.com
      - agent1.ord1.com
      - agent2.ord1.com
      - agent3.ord1.com
      - agent4.ord1.com
      - agent5.ord1.com

etc.
```
